import assert from 'node:assert/strict'
import test from 'node:test'
import { CompanionNotificationQueue, REMINDER_INTERVAL, TASK_INACTIVITY_MS } from '../src/renderer/components/companionNotificationQueue.ts'

const notice = (id, overrides = {}) => ({ id, key: `${id}:question:1`, provider: 'codex',
  title: id, detail: '需要确认什么？', phase: 'attention', repeatable: true, ...overrides })

test('all cards appear immediately while separate speech requests stay FIFO', () => {
  const q = new CompanionNotificationQueue()
  const a = notice('a'), b = notice('b')
  q.update([a, b], 0)
  assert.equal(q.visible.size, 2)
  assert.equal(q.take().id, 'a')
  assert.equal(q.take(), null)
  q.started(a.key)
  assert.deepEqual([...q.visible.keys()], ['a', 'b'])
  q.finished(a.key, 100)
  assert.equal(q.take().id, 'b')
  assert.equal(q.visible.has('b'), true)
})

test('resolved queued items vanish, while started narration is allowed to finish', () => {
  const q = new CompanionNotificationQueue()
  const a = notice('a'), b = notice('b')
  q.update([a, b], 0); q.take(); q.started(a.key)
  q.update([], 20)
  assert.equal(q.visible.has('a'), false)
  assert.equal(q.active.speaking, true)
  assert.deepEqual(q.queue, [])
  q.finished(a.key, 30)
  assert.equal(q.visible.size, 0)
  assert.equal(q.due.size, 0)
})

test('repeat begins ten minutes after finish, never accumulates, and new requests rearm', () => {
  const q = new CompanionNotificationQueue()
  const a = notice('a')
  q.update([a], 0); q.take(); q.started(a.key); q.finished(a.key, 200)
  q.tick(REMINDER_INTERVAL + 199); assert.equal(q.queue.length, 0)
  q.tick(REMINDER_INTERVAL + 200); q.tick(REMINDER_INTERVAL * 3)
  assert.deepEqual(q.queue, [a.key])
  q.update([], REMINDER_INTERVAL * 3)
  const next = notice('a', { key: 'a:question:2' })
  q.update([next], REMINDER_INTERVAL * 3)
  assert.equal(q.take().key, next.key)
})

test('muting preserves original cards and unmuting does not replay a backlog', () => {
  const q = new CompanionNotificationQueue()
  const a = notice('a'), b = notice('b')
  q.update([a], 0); q.take(); q.started(a.key)
  q.setEnabled(false, 1); q.update([a, b], 2)
  assert.equal(q.active, null)
  assert.equal(q.visible.size, 2)
  q.setEnabled(true, 3)
  assert.equal(q.take(), null)
  q.tick(REMINDER_INTERVAL + 3)
  assert.equal(q.queue.length, 0, 'unmuting must not schedule a first delivery for skipped notices')
})

test('chat preemption preserves reminder order and stale callbacks cannot advance it', () => {
  const q = new CompanionNotificationQueue()
  const a = notice('a'), b = notice('b')
  q.update([a, b], 0); q.take(); q.started(a.key); q.preempted(a.key)
  assert.equal(q.take().key, a.key)
  q.finished('stale', 1)
  assert.equal(q.active.task.key, a.key)
  q.finished(a.key, 2)
  assert.equal(q.take().key, b.key)
})

test('ordinary progress is visual only; failures reveal original text; unread ends repeat only with evidence', () => {
  const q = new CompanionNotificationQueue()
  const running = notice('r', { phase: 'running' })
  const end = notice('e', { phase: 'ready', key: 'e:turn-1', repeatable: true })
  q.update([running, end], 0)
  assert.equal(q.visible.get('r'), running)
  assert.equal(q.take(), end)
  q.finished(end.key, 20, true)
  assert.equal(q.visible.get('e').detail, end.detail)
  assert.equal(q.faults.has(end.key), true)
  assert.equal(q.due.get(end.key), 20 + REMINDER_INTERVAL)
  q.update([running], 30)
  assert.equal(q.due.size, 0)
})

test('Amadeus Work already has narration and must not be announced twice', () => {
  const q = new CompanionNotificationQueue()
  const work = notice('work', { announce: false })
  q.update([work], 0)
  assert.equal(q.visible.get('work'), work)
  assert.equal(q.take(), null)
  q.setEnabled(false, 1); q.setEnabled(true, 2); q.tick(REMINDER_INTERVAL * 2)
  assert.equal(q.take(), null)
})

test('saved title changes reach pending and visible cards without reannouncing', () => {
  const q = new CompanionNotificationQueue()
  const original = notice('a', { title: '等待标题', repeatable: false })
  q.update([original], 0); q.take()
  const named = { ...original, title: '真正的任务标题' }
  q.update([named], 1)
  assert.equal(q.visible.get('a').title, named.title)
  q.started(original.key)
  assert.equal(q.visible.get('a').title, named.title)
  q.finished(original.key, 2)
  const renamed = { ...named, title: '修改后的标题' }
  q.update([renamed], 3)
  assert.equal(q.visible.get('a').title, renamed.title)
  assert.equal(q.take(), null)
})

test('running, question, and completion replace the same card without a blank interval or stale speech rollback', () => {
  const q = new CompanionNotificationQueue()
  const running = notice('a', { key: 'a:running', phase: 'running' })
  const question = notice('a')
  const ready = notice('a', { key: 'a:ready', phase: 'ready', repeatable: false })
  q.update([running], 0)
  q.update([question], 1)
  assert.equal(q.visible.get('a').phase, 'attention')
  q.take(); q.started(question.key)
  q.update([ready], 2)
  assert.equal(q.visible.get('a').phase, 'ready')
  q.finished(question.key, 3)
  assert.equal(q.visible.get('a').phase, 'ready')
  assert.equal(q.take().key, ready.key)
})

test('all phases use eight hours of source inactivity; polling and renaming never extend it', () => {
  const q = new CompanionNotificationQueue(false)
  const tasks = ['ready', 'running', 'attention', 'blocked'].map(phase => notice(phase, { phase, lastActivityAt: 0 }))
  q.update(tasks, 0)
  q.update(tasks.map(task => ({ ...task, title: '改名' })), TASK_INACTIVITY_MS - 1)
  assert.equal(q.visible.size, 4)
  q.tick(TASK_INACTIVITY_MS)
  assert.equal(q.fading.size, 4)
  q.tick(TASK_INACTIVITY_MS + 500)
  q.update(tasks, TASK_INACTIVITY_MS + 1000)
  assert.equal(q.visible.size, 0)
  const progress = { ...tasks[1], lastActivityAt: TASK_INACTIVITY_MS + 2000 }
  q.update([progress], TASK_INACTIVITY_MS + 2000)
  assert.equal(q.visible.get(progress.id), progress, 'new tool activity can restore the same notification key')
})

test('recent completed cards survive reopening without a fresh eight-hour allowance or old speech', () => {
  const q = new CompanionNotificationQueue(false)
  const end = notice('e', { phase: 'ready', repeatable: false, announce: false, lastActivityAt: 0 })
  q.update([end], TASK_INACTIVITY_MS - 1000)
  assert.equal(q.visible.size, 1)
  q.setEnabled(true, TASK_INACTIVITY_MS - 500)
  assert.equal(q.take(), null)
  q.tick(TASK_INACTIVITY_MS); q.tick(TASK_INACTIVITY_MS + 500)
  assert.equal(q.visible.size, 0)
  assert.equal(q.take(), null)
})

test('manual dismissal survives reopening and repeated snapshots, new actual activity restores it', () => {
  const q = new CompanionNotificationQueue()
  const task = notice('a', { lastActivityAt: 100 })
  q.update([task], 100)
  q.dismiss(task.id)
  assert.equal(q.take(), null)
  assert.equal(q.visible.size, 0)
  const reopened = new CompanionNotificationQueue(true, Object.fromEntries(q.dismissed))
  reopened.update([task], 200)
  assert.equal(reopened.visible.size, 0)
  assert.equal(reopened.take(), null)
  reopened.update([{ ...task, lastActivityAt: 300, key: 'a:next-question' }], 300)
  assert.equal(reopened.visible.size, 1)
  assert.equal(reopened.take().key, 'a:next-question')
})

test('voice playback and reading do not reset source activity, reading only holds an expiring card', () => {
  const q = new CompanionNotificationQueue()
  const end = notice('e', { phase: 'ready', repeatable: false, lastActivityAt: 0 })
  q.update([end], 0); q.take(); q.started(end.key)
  q.finished(end.key, TASK_INACTIVITY_MS - 1000)
  q.hold(end.id, true)
  q.tick(TASK_INACTIVITY_MS + 1000)
  assert.equal(q.visible.size, 1)
  q.hold(end.id, false)
  q.tick(TASK_INACTIVITY_MS + 2000); q.tick(TASK_INACTIVITY_MS + 2500)
  assert.equal(q.visible.size, 0)
})

test('provider snapshots without timestamps extend retention only on actual payload changes', () => {
  const q = new CompanionNotificationQueue(false)
  const run = notice('r', { phase: 'running', announce: false })
  q.update([run], 0)
  q.update([{ ...run, title: 'renamed' }], TASK_INACTIVITY_MS - 1)
  assert.equal(q.activity.get(run.id), 0)
  q.update([{ ...run, detail: 'new progress' }], TASK_INACTIVITY_MS - 1)
  q.tick(TASK_INACTIVITY_MS + 1)
  assert.equal(q.visible.size, 1)
  assert.equal(q.fading.size, 0)
})

test('each notification has at most one ten-minute follow-up, including after reopening', () => {
  const a = notice('a')
  const q = new CompanionNotificationQueue()
  q.update([a], 0); q.take(); q.finished(a.key, 100)
  const restored = new CompanionNotificationQueue(true, {}, q.history())
  restored.update([], 200)
  restored.update([a], 300)
  assert.equal(restored.take(), null)
  restored.tick(REMINDER_INTERVAL + 100)
  assert.equal(restored.take().key, a.key)
  restored.finished(a.key, REMINDER_INTERVAL + 200)
  restored.tick(REMINDER_INTERVAL * 3)
  assert.equal(restored.take(), null)
  const next = notice('a', { key: 'a:question:2' })
  restored.update([next], REMINDER_INTERVAL * 3)
  assert.equal(restored.take().key, next.key)
})

test('local acknowledgement keeps the card and cancels only this notice, even across reopening', () => {
  const a = notice('a')
  const q = new CompanionNotificationQueue()
  q.update([a], 0); q.take(); q.finished(a.key, 100)
  q.acknowledge(a.key)
  assert.equal(q.visible.get(a.id).phase, 'attention')
  const restored = new CompanionNotificationQueue(true, {}, q.history())
  restored.update([a], 200)
  restored.tick(REMINDER_INTERVAL * 2)
  assert.equal(restored.take(), null)
  assert.equal(restored.visible.size, 1)
  assert.ok(restored.acknowledged.has(a.key))
})

test('busy deferral preserves FIFO without consuming either permitted delivery', () => {
  const q = new CompanionNotificationQueue()
  const a = notice('a'), b = notice('b')
  q.update([a,b], 0)
  for (let i = 0; i < 5; i++) { assert.equal(q.take().id, 'a'); q.preempted(a.key) }
  assert.equal(q.deliveries.size, 0)
  assert.deepEqual(q.queue, [a.key,b.key])
})
