"""Generate deterministic Mermaid views from architecture YAML models."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[2]
MODEL_DIR = ROOT / "architecture" / "model"
VIEW_DIR = ROOT / "architecture" / "views"


def _load(name: str) -> dict[str, Any]:
    path = MODEL_DIR / name
    with path.open("r", encoding="utf-8") as stream:
        value = yaml.safe_load(stream)
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return value


def _safe_id(value: str) -> str:
    text = re.sub(r"[^A-Za-z0-9_]", "_", str(value))
    if not text or text[0].isdigit():
        text = f"n_{text}"
    return text


def _label(value: Any) -> str:
    return " ".join(str(value or "").replace('"', "'").split())


def _state_views(model: dict[str, Any]) -> dict[str, str]:
    machines = model.get("machines")
    if not isinstance(machines, dict):
        raise ValueError("states.yaml: machines must be a mapping")
    outputs: dict[str, str] = {}
    for machine_id, raw_machine in machines.items():
        if not isinstance(raw_machine, dict):
            raise ValueError(f"states.yaml: machine {machine_id!r} must be a mapping")
        states = raw_machine.get("states")
        transitions = raw_machine.get("transitions")
        if not isinstance(states, dict) or not isinstance(transitions, list):
            raise ValueError(f"states.yaml: machine {machine_id!r} needs states and transitions")
        lines = [
            "%% Generated by tools/architecture/generate_views.py; do not edit.",
            "stateDiagram-v2",
            "    direction LR",
        ]
        for state_id, description in states.items():
            lines.append(f'    state "{_label(state_id)}" as {_safe_id(state_id)}')
            lines.append(f"    note right of {_safe_id(state_id)}")
            lines.append(f"        {_label(description)}")
            lines.append("    end note")
        for transition in transitions:
            if not isinstance(transition, dict):
                raise ValueError(f"states.yaml: invalid transition in {machine_id!r}")
            source = str(transition.get("from") or "")
            target = str(transition.get("to") or "")
            if source not in {"__start__", "__end__"} and source not in states:
                raise ValueError(f"states.yaml: unknown source state {source!r}")
            if target not in {"__start__", "__end__"} and target not in states:
                raise ValueError(f"states.yaml: unknown target state {target!r}")
            source_id = "[*]" if source in {"__start__", "__end__"} else _safe_id(source)
            target_id = "[*]" if target in {"__start__", "__end__"} else _safe_id(target)
            label = _label(transition.get("label"))
            lines.append(f"    {source_id} --> {target_id}" + (f": {label}" if label else ""))
        outputs[f"state-{machine_id.replace('_', '-')}.mmd"] = "\n".join(lines) + "\n"
    return outputs


def _permission_view(model: dict[str, Any]) -> str:
    actors = model.get("actors")
    capabilities = model.get("capabilities")
    canvas_entry = model.get("canvas_entry")
    if not isinstance(actors, dict) or not isinstance(capabilities, list):
        raise ValueError("permissions.yaml needs actors and capabilities")

    used_actor_ids: set[str] = set()
    for capability in capabilities:
        if not isinstance(capability, dict):
            raise ValueError("permissions.yaml: each capability must be a mapping")
        for key in ("requested_by", "gate", "executor", "resource"):
            actor_id = str(capability.get(key) or "")
            if actor_id not in actors:
                raise ValueError(f"permissions.yaml: unknown actor {actor_id!r} for {key}")
            used_actor_ids.add(actor_id)
    if isinstance(canvas_entry, dict):
        for key in ("from", "through", "to"):
            actor_id = str(canvas_entry.get(key) or "")
            if actor_id not in actors:
                raise ValueError(f"permissions.yaml: unknown canvas entry actor {actor_id!r}")
            used_actor_ids.add(actor_id)

    lines = [
        "%% Generated by tools/architecture/generate_views.py; do not edit.",
        "flowchart LR",
        '    user(["User intent"])',
        "    subgraph requesters[Request surfaces and callers]",
    ]
    for actor_id in sorted(used_actor_ids):
        actor = actors[actor_id]
        if not isinstance(actor, dict):
            raise ValueError(f"permissions.yaml: actor {actor_id!r} must be a mapping")
        if str(actor.get("kind")) in {"request_surface", "untrusted_surface"}:
            lines.append(f'        actor_{_safe_id(actor_id)}["{_label(actor.get("label"))}"]')
    lines.append("    end")
    lines.append("    subgraph gates[Host-owned decision boundaries]")
    for actor_id in sorted(used_actor_ids):
        actor = actors[actor_id]
        if str(actor.get("kind")) in {"security_boundary", "validation_boundary", "authority", "durable_authority"}:
            lines.append(f'        actor_{_safe_id(actor_id)}["{_label(actor.get("label"))}"]')
    lines.append("    end")
    lines.append("    subgraph executors[Executors and resources]")
    for actor_id in sorted(used_actor_ids):
        actor = actors[actor_id]
        if str(actor.get("kind")) in {"executor", "resource"}:
            lines.append(f'        actor_{_safe_id(actor_id)}["{_label(actor.get("label"))}"]')
    lines.append("    end")

    for index, capability in enumerate(capabilities, start=1):
        cap_node = f"cap_{index}"
        cap_label = _label(capability.get("label") or capability.get("id"))
        risk = _label(capability.get("risk"))
        approval = _label(capability.get("approval"))
        lines.append(f'    {cap_node}{{"{cap_label}<br/>{risk} · {approval}"}}')
        requester = f"actor_{_safe_id(str(capability['requested_by']))}"
        gate = f"actor_{_safe_id(str(capability['gate']))}"
        executor = f"actor_{_safe_id(str(capability['executor']))}"
        resource = f"actor_{_safe_id(str(capability['resource']))}"
        lines.append(f'    {requester} -->|"{_label(capability.get("id"))}"| {cap_node}')
        lines.append(f"    {cap_node} --> {gate}")
        lines.append(f"    {gate} --> {executor}")
        if executor != resource:
            lines.append(f"    {executor} --> {resource}")
    requester_nodes = [
        f"actor_{_safe_id(actor_id)}"
        for actor_id in used_actor_ids
        if str(actors[actor_id].get("kind")) in {"request_surface", "untrusted_surface"}
    ]
    for requester_node in sorted(requester_nodes):
        lines.append(f"    user --> {requester_node}")
    if isinstance(canvas_entry, dict):
        source = f"actor_{_safe_id(str(canvas_entry['from']))}"
        through = f"actor_{_safe_id(str(canvas_entry['through']))}"
        target = f"actor_{_safe_id(str(canvas_entry['to']))}"
        lines.append(f'    {source} -->|"allowlisted canvas action"| {through}')
        lines.append(f"    {through} --> {target}")
    lines.append("    classDef capability fill:#fff3e0,stroke:#ef6c00,color:#111")
    lines.append("    classDef boundary fill:#ffebee,stroke:#c62828,color:#111")
    lines.append("    class cap_1,cap_2,cap_3,cap_4,cap_5,cap_6 capability")
    boundary_nodes = [
        f"actor_{_safe_id(actor_id)}"
        for actor_id in used_actor_ids
        if str(actors[actor_id].get("kind")) in {"security_boundary", "validation_boundary", "authority"}
    ]
    if boundary_nodes:
        lines.append(f"    class {','.join(sorted(boundary_nodes))} boundary")
    return "\n".join(lines) + "\n"


def _interaction_views(model: dict[str, Any]) -> dict[str, str]:
    scenarios = model.get("scenarios")
    if not isinstance(scenarios, dict):
        raise ValueError("interactions.yaml: scenarios must be a mapping")
    outputs: dict[str, str] = {}
    for scenario_id, scenario in scenarios.items():
        if not isinstance(scenario, dict):
            raise ValueError(f"interactions.yaml: scenario {scenario_id!r} must be a mapping")
        participants = scenario.get("participants")
        steps = scenario.get("steps")
        if not isinstance(participants, dict) or not isinstance(steps, list):
            raise ValueError(f"interactions.yaml: scenario {scenario_id!r} needs participants and steps")
        lines = [
            "%% Generated by tools/architecture/generate_views.py; do not edit.",
            "sequenceDiagram",
            "    autonumber",
        ]
        for participant_id, participant_label in participants.items():
            lines.append(f'    participant {_safe_id(participant_id)} as {_label(participant_label)}')
        for step in steps:
            if not isinstance(step, dict):
                raise ValueError(f"interactions.yaml: invalid step in {scenario_id!r}")
            step_type = str(step.get("type") or "message")
            label = _label(step.get("label"))
            if step_type == "message":
                source = str(step.get("from") or "")
                target = str(step.get("to") or "")
                if source not in participants or target not in participants:
                    raise ValueError(f"interactions.yaml: unknown participant in {scenario_id!r}")
                arrow = "-->>" if step.get("arrow") == "reply" else "->>"
                lines.append(f"    {_safe_id(source)}{arrow}{_safe_id(target)}: {label}")
            elif step_type == "note":
                over = step.get("over")
                if not isinstance(over, list) or not over or any(item not in participants for item in over):
                    raise ValueError(f"interactions.yaml: invalid note participants in {scenario_id!r}")
                joined = ",".join(_safe_id(item) for item in over)
                lines.append(f"    Note over {joined}: {label}")
            elif step_type == "loop_start":
                lines.append(f"    loop {label}")
            elif step_type == "loop_end":
                lines.append("    end")
            elif step_type == "alt_start":
                lines.append(f"    alt {label}")
            elif step_type == "else":
                lines.append(f"    else {label}")
            elif step_type == "alt_end":
                lines.append("    end")
            else:
                raise ValueError(f"interactions.yaml: unsupported step type {step_type!r}")
        outputs[f"sequence-{scenario_id.replace('_', '-')}.mmd"] = "\n".join(lines) + "\n"
    return outputs


def _expected_outputs() -> dict[str, str]:
    outputs = _state_views(_load("states.yaml"))
    outputs["authority-boundaries.mmd"] = _permission_view(_load("permissions.yaml"))
    outputs.update(_interaction_views(_load("interactions.yaml")))
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated views differ")
    args = parser.parse_args()
    outputs = _expected_outputs()
    stale: list[str] = []
    for name, expected in outputs.items():
        path = VIEW_DIR / name
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == expected:
            continue
        stale.append(str(path.relative_to(ROOT)))
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8", newline="\n")
    if stale and args.check:
        print("Architecture views are stale:")
        for path in stale:
            print(f"  {path}")
        return 1
    action = "checked" if args.check else "generated"
    print(f"{action} {len(outputs)} architecture views")
    return 0


if __name__ == "__main__":
    sys.exit(main())
